### ISSUE TITLE
Implementación de Hilos dentro del Proyecto 

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo-buscadores-de-datos#1]
[PRACTICA DE IMPLEMNETACIÓN DE HILOS .pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo-buscadores-de-datos/files/15124477/PRACTICA.DE.IMPLEMNETACION.DE.HILOS.pdf)

* Roldan Uriel Arcadio Ávila
* Pedro Garcia Garcia
* Ariadna Monserrat López Aparicio

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, han obtenido un 20% de 20%, cumpliedo con todos los requerimientos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
